apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: conversao-temperatura-pod
        image: rebornsilverio/conversao-temperatura
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080

